//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Types.Ipaffs;

/// <summary>
/// 
/// </summary>
public partial class IpaffsComplementParameterSet  //
{


    /// <summary>
    /// UUID used to match commodityComplement to its complementParameter set. CHEDPP only
    /// </summary
    [JsonPropertyName("uniqueComplementID")]
    public string? UniqueComplementId { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("complementID")]
    public int? ComplementId { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("speciesID")]
    public string? SpeciesId { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("keyDataPair")]
    [JsonConverter(typeof(KeyDataPairsToDictionaryStringObjectJsonConverter))]
    public IDictionary<string, object>? KeyDataPairs { get; set; }

	
    /// <summary>
    /// Catch certificate details
    /// </summary
    [JsonPropertyName("catchCertificates")]
    public IpaffsCatchCertificates[]? CatchCertificates { get; set; }

	
    /// <summary>
    /// Data used to identify the complements inside an IMP consignment
    /// </summary
    [JsonPropertyName("identifiers")]
    public IpaffsIdentifiers[]? Identifiers { get; set; }

	}


