//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Types.Ipaffs;

/// <summary>
/// Details of Control (Part 3)
/// </summary>
public partial class IpaffsControl  //
{


    /// <summary>
    /// Feedback information of Control
    /// </summary
    [JsonPropertyName("feedbackInformation")]
    public IpaffsFeedbackInformation? FeedbackInformation { get; set; }

	
    /// <summary>
    /// Details on re-export
    /// </summary
    [JsonPropertyName("detailsOnReExport")]
    public IpaffsDetailsOnReExport? DetailsOnReExport { get; set; }

	
    /// <summary>
    /// Official inspector
    /// </summary
    [JsonPropertyName("officialInspector")]
    public IpaffsOfficialInspector? OfficialInspector { get; set; }

	
    /// <summary>
    /// Is the consignment leaving UK borders?
    /// </summary
    [JsonPropertyName("consignmentLeave")]
    public IpaffsControlConsignmentLeaveEnum? ConsignmentLeave { get; set; }

	}


