//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.ComponentModel.DataAnnotations.Schema;
using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;
using JsonApiDotNetCore.MongoDb.Resources;
using MongoDB.Bson.Serialization.Attributes;
using TdmPrototypeBackend.Types.Extensions;


namespace TdmPrototypeBackend.Types.VehicleMovement;

/// <summary>
/// 
/// </summary>
[Resource]
public partial class Gmr : IMongoIdentifiable
{
    [JsonIgnore]
    public string Type { get; set; } = "gmrs";

    [JsonIgnore]
    public virtual string? Id
    {
        get => GmrId;
        set => GmrId = value;
    }

    // TODO : this is currently being written on the wire by the json api client
    /// <inheritdoc />
    [BsonIgnore]
    [JsonIgnore]
    // [NotMapped]
    [Attr]
    public string? StringId
    {
        get => Id;
        set => Id = value;
    }

    /// <inheritdoc />
    [BsonIgnore]
    [JsonIgnore]
    [NotMapped]
    // [Attr]
    public string? LocalId { get; set; }

    [Attr]
    public List<AuditEntry> AuditEntries { get; set; } = new List<AuditEntry>();

    [Attr]
    [ApiIgnore]
    [JsonPropertyName("relationships")]
    public GmrTdmRelationships Relationships { get; set; } = new GmrTdmRelationships();

}


