//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;

namespace TdmPrototypeBackend.Types.VehicleMovement;

    /// <summary>
    /// Information about an inspection that is required
    /// </summary>
public partial class ReportToLocations  {


        /// <summary>
        /// An inspectionTypeId from GVMS Reference Data denoting the type of inspection that needs to be performed on the vehicle.
        /// </summary>
        [Attr]
        [JsonPropertyName("inspectionTypeId")]
        public string? InspectionTypeId { get; set; }
    
}


