//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Alvs;

public static class ServiceHeaderMapper
{
    public static Tdm.Model.Alvs.ServiceHeader Map(Tdm.Types.Alvs.ServiceHeader from)
    {
        if (from is null)
        {
            return default!;
        }

        var to = new Tdm.Model.Alvs.ServiceHeader();
        to.SourceSystem = from.SourceSystem;
        to.DestinationSystem = from.DestinationSystem;
        to.CorrelationId = from.CorrelationId;
        to.ServiceCallTimestamp = from.ServiceCallTimestamp;
        return to;
    }
}



