//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace TdmPrototypeBackend.Types.Alvs;

    /// <summary>
    /// 
    /// </summary>
public partial class Document  //
{


		/// <summary>
        /// 
        /// </summary>
        [Attr]
        [JsonPropertyName("DocumentCode")]
		public  string? DocumentCode { get; set; }
    
		/// <summary>
        /// 
        /// </summary>
        [Attr]
        [JsonPropertyName("DocumentReference")]
		public  string? DocumentReference { get; set; }
    
		/// <summary>
        /// 
        /// </summary>
        [Attr]
        [JsonPropertyName("DocumentStatus")]
		public  string? DocumentStatus { get; set; }
    
		/// <summary>
        /// 
        /// </summary>
        [Attr]
        [JsonPropertyName("DocumentControl")]
		public  string? DocumentControl { get; set; }
    
		/// <summary>
        /// 
        /// </summary>
        [Attr]
        [JsonPropertyName("DocumentQuantity")]
		public  decimal? DocumentQuantity { get; set; }
    
}


