//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Types.Alvs;

/// <summary>
/// Message sent to the server to send an ALVSClearanceRequest.
/// </summary>
public partial class AlvsClearanceRequestPost  //
{


    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("xmlSchemaVersion")]
    public string? XmlSchemaVersion { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("userIdentification")]
    public string? UserIdentification { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("userPassword")]
    public string? UserPassword { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("sendingDate")]
    public string? SendingDate { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("alvsClearanceRequest")]
    public AlvsClearanceRequest? AlvsClearanceRequest { get; set; }

	}


