//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Types.Alvs;

/// <summary>
/// 
/// </summary>
public partial class Check  //
{


    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("checkCode")]
    public string? CheckCode { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("departmentCode")]
    public string? DepartmentCode { get; set; }

	}


