//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Types.Alvs;

/// <summary>
/// 
/// </summary>
public partial class Document  //
{


    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("documentCode")]
    public string? DocumentCode { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("documentReference")]
    public string? DocumentReference { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("documentStatus")]
    public string? DocumentStatus { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("documentControl")]
    public string? DocumentControl { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("documentQuantity")]
    public decimal? DocumentQuantity { get; set; }

	}


