//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Types.Alvs;

/// <summary>
/// 
/// </summary>
public partial class ServiceHeader  //
{


    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("sourceSystem")]
    public string? SourceSystem { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("destinationSystem")]
    public string? DestinationSystem { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("correlationId")]
    public string? CorrelationId { get; set; }

	
    /// <summary>
    /// 
    /// </summary
    [JsonPropertyName("serviceCallTimestamp")]
    public DateTime? ServiceCallTimestamp { get; set; }

	}


