//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Model.Ipaffs;

/// <summary>
/// Impact of transport on animals
/// </summary>
public partial class IpaffsImpactOfTransportOnAnimals  //
{


    /// <summary>
    /// Number of dead animals specified by units
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Number of dead animals specified by units")]
    public int? NumberOfDeadAnimals { get; set; }

	
    /// <summary>
    /// Unit used for specifying number of dead animals (percent or units)
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Unit used for specifying number of dead animals (percent or units)")]
    public string? NumberOfDeadAnimalsUnit { get; set; }

	
    /// <summary>
    /// Number of unfit animals
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Number of unfit animals")]
    public int? NumberOfUnfitAnimals { get; set; }

	
    /// <summary>
    /// Unit used for specifying number of unfit animals (percent or units)
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Unit used for specifying number of unfit animals (percent or units)")]
    public string? NumberOfUnfitAnimalsUnit { get; set; }

	
    /// <summary>
    /// Number of births or abortions (unit)
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Number of births or abortions (unit)")]
    public int? NumberOfBirthOrAbortion { get; set; }

	}


