//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Model.Ipaffs;

/// <summary>
/// consignment checks
/// </summary>
public partial class IpaffsConsignmentCheck  //
{


    /// <summary>
    /// Does it conform EU standards
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Does it conform EU standards")]
    public string? EuStandard { get; set; }

	
    /// <summary>
    /// Result of additional guarantees
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Result of additional guarantees")]
    public string? AdditionalGuarantees { get; set; }

	
    /// <summary>
    /// Result of document check
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Result of document check")]
    public string? DocumentCheckResult { get; set; }

	
    /// <summary>
    /// Result of national requirements check
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Result of national requirements check")]
    public string? NationalRequirements { get; set; }

	
    /// <summary>
    /// Was identity check done
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Was identity check done")]
    public bool? IdentityCheckDone { get; set; }

	
    /// <summary>
    /// Type of identity check performed
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Type of identity check performed")]
    [MongoDB.Bson.Serialization.Attributes.BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public IpaffsConsignmentCheckIdentityCheckTypeEnum? IdentityCheckType { get; set; }

	
    /// <summary>
    /// Result of identity check
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Result of identity check")]
    public string? IdentityCheckResult { get; set; }

	
    /// <summary>
    /// What was the reason for skipping identity check
    /// </summary
    [Attr]
    [System.ComponentModel.Description("What was the reason for skipping identity check")]
    [MongoDB.Bson.Serialization.Attributes.BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public IpaffsConsignmentCheckIdentityCheckNotDoneReasonEnum? IdentityCheckNotDoneReason { get; set; }

	
    /// <summary>
    /// Was physical check done
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Was physical check done")]
    public bool? PhysicalCheckDone { get; set; }

	
    /// <summary>
    /// Result of physical check
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Result of physical check")]
    public string? PhysicalCheckResult { get; set; }

	
    /// <summary>
    /// What was the reason for skipping physical check
    /// </summary
    [Attr]
    [System.ComponentModel.Description("What was the reason for skipping physical check")]
    [MongoDB.Bson.Serialization.Attributes.BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum? PhysicalCheckNotDoneReason { get; set; }

	
    /// <summary>
    /// Other reason to not do physical check
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Other reason to not do physical check")]
    public string? PhysicalCheckOtherText { get; set; }

	
    /// <summary>
    /// Welfare check
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Welfare check")]
    public string? WelfareCheck { get; set; }

	
    /// <summary>
    /// Number of animals checked
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Number of animals checked")]
    public int? NumberOfAnimalsChecked { get; set; }

	
    /// <summary>
    /// Were laboratory tests done
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Were laboratory tests done")]
    public bool? LaboratoryCheckDone { get; set; }

	
    /// <summary>
    /// Result of laboratory tests
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Result of laboratory tests")]
    public string? LaboratoryCheckResult { get; set; }

	}


