//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Model.Ipaffs;

/// <summary>
/// Result of risk assessment by the risk scorer
/// </summary>
public partial class IpaffsRiskAssessmentResult  //
{


    /// <summary>
    /// List of risk assessed commodities
    /// </summary
    [Attr]
    [System.ComponentModel.Description("List of risk assessed commodities")]
    public IpaffsCommodityRiskResult[]? CommodityResults { get; set; }

	
    /// <summary>
    /// Date and time of assessment
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Date and time of assessment")]
    public DateTime? AssessmentDateTime { get; set; }

	}


