//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Model.Ipaffs;

/// <summary>
/// Details of the seal check
/// </summary>
public partial class IpaffsSealCheck  //
{


    /// <summary>
    /// Is seal check satisfactory
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Is seal check satisfactory")]
    public bool? Satisfactory { get; set; }

	
    /// <summary>
    /// reason for not satisfactory
    /// </summary
    [Attr]
    [System.ComponentModel.Description("reason for not satisfactory")]
    public string? Reason { get; set; }

	
    /// <summary>
    /// Official inspector
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Official inspector")]
    public IpaffsOfficialInspector? OfficialInspector { get; set; }

	
    /// <summary>
    /// date and time of seal check
    /// </summary
    [Attr]
    [System.ComponentModel.Description("date and time of seal check")]
    public DateTime? DateTimeOfCheck { get; set; }

	}


