//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Model.Ipaffs;

/// <summary>
/// Billing postal address
/// </summary>
public partial class IpaffsPostalAddress  //
{


    /// <summary>
    /// 1st line of address
    /// </summary
    [Attr]
    [System.ComponentModel.Description("1st line of address")]
    public string? AddressLine1 { get; set; }

	
    /// <summary>
    /// 2nd line of address
    /// </summary
    [Attr]
    [System.ComponentModel.Description("2nd line of address")]
    public string? AddressLine2 { get; set; }

	
    /// <summary>
    /// 3rd line of address
    /// </summary
    [Attr]
    [System.ComponentModel.Description("3rd line of address")]
    public string? AddressLine3 { get; set; }

	
    /// <summary>
    /// 4th line of address
    /// </summary
    [Attr]
    [System.ComponentModel.Description("4th line of address")]
    public string? AddressLine4 { get; set; }

	
    /// <summary>
    /// 3rd line of address
    /// </summary
    [Attr]
    [System.ComponentModel.Description("3rd line of address")]
    public string? County { get; set; }

	
    /// <summary>
    /// City or town name
    /// </summary
    [Attr]
    [System.ComponentModel.Description("City or town name")]
    public string? CityOrTown { get; set; }

	
    /// <summary>
    /// Post code
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Post code")]
    public string? PostalCode { get; set; }

	}


