//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Model.Ipaffs;

/// <summary>
/// Details on re-export
/// </summary>
public partial class IpaffsDetailsOnReExport  //
{


    /// <summary>
    /// Date of re-export
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Date of re-export")]
    public DateTime? Date { get; set; }

	
    /// <summary>
    /// Number of vehicle
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Number of vehicle")]
    public string? MeansOfTransportNo { get; set; }

	
    /// <summary>
    /// Type of transport to be used
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Type of transport to be used")]
    [MongoDB.Bson.Serialization.Attributes.BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public IpaffsDetailsOnReExportTransportTypeEnum? TransportType { get; set; }

	
    /// <summary>
    /// Document issued for re-export
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Document issued for re-export")]
    public string? Document { get; set; }

	
    /// <summary>
    /// Two letter ISO code for country of re-dispatching
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Two letter ISO code for country of re-dispatching")]
    public string? CountryOfReDispatching { get; set; }

	
    /// <summary>
    /// Exit BIP (where consignment will leave the country)
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Exit BIP (where consignment will leave the country)")]
    public string? ExitBip { get; set; }

	}


