//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace Tdm.Model.Ipaffs;

/// <summary>
/// 
/// </summary>
public partial class IpaffsIdentificationDetails  //
{


    /// <summary>
    /// Identification detail
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Identification detail")]
    public string? IdentificationDetail { get; set; }

	
    /// <summary>
    /// Identification description
    /// </summary
    [Attr]
    [System.ComponentModel.Description("Identification description")]
    public string? IdentificationDescription { get; set; }

	}


