//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsSealCheckMapper
{
	public static Tdm.Model.Ipaffs.IpaffsSealCheck Map(Tdm.Types.Ipaffs.IpaffsSealCheck from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsSealCheck ();
to.Satisfactory = from.Satisfactory;
            to.Reason = from.Reason;
            to.OfficialInspector = IpaffsOfficialInspectorMapper.Map(from?.OfficialInspector);
                to.DateTimeOfCheck = from.DateTimeOfCheck;
            	return to;
	}
}

