//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsAccompanyingDocumentDocumentTypeEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum? Map(Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.AirWaybill => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.AirWaybill,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.BillOfLading => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.BillOfLading,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CargoManifest => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CargoManifest,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CatchCertificate => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CatchCertificate,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CommercialDocument => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CommercialDocument,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CommercialInvoice => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CommercialInvoice,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ConformityCertificate => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ConformityCertificate,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ContainerManifest => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ContainerManifest,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CustomsDeclaration => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.CustomsDeclaration,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.Docom => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.Docom,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.HealthCertificate => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.HealthCertificate,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.HeatTreatmentCertificate => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.HeatTreatmentCertificate,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ImportPermit => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ImportPermit,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.InspectionCertificate => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.InspectionCertificate,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.Itahc => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.Itahc,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.JourneyLog => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.JourneyLog,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LaboratorySamplingResultsForAflatoxin => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LaboratorySamplingResultsForAflatoxin,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LatestVeterinaryHealthCertificate => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LatestVeterinaryHealthCertificate,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LetterOfAuthority => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LetterOfAuthority,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LicenseOrAuthorisation => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.LicenseOrAuthorisation,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.MycotoxinCertification => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.MycotoxinCertification,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.OriginCertificate => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.OriginCertificate,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.Other => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.Other,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.PhytosanitaryCertificate => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.PhytosanitaryCertificate,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ProcessingStatement => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ProcessingStatement,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ProofOfStorage => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ProofOfStorage,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.RailwayBill => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.RailwayBill,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.SeaWaybill => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.SeaWaybill,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.VeterinaryHealthCertificate => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.VeterinaryHealthCertificate,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ListOfIngredients => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.ListOfIngredients,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.PackingList => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.PackingList,
    Tdm.Types.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.RoadConsignmentNote => Tdm.Model.Ipaffs.IpaffsAccompanyingDocumentDocumentTypeEnum.RoadConsignmentNote,
     
};
}
        

}


