//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsBillingInformationMapper
{
	public static Tdm.Model.Ipaffs.IpaffsBillingInformation Map(Tdm.Types.Ipaffs.IpaffsBillingInformation from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsBillingInformation ();
to.IsConfirmed = from.IsConfirmed;
            to.EmailAddress = from.EmailAddress;
            to.PhoneNumber = from.PhoneNumber;
            to.ContactName = from.ContactName;
            to.PostalAddress = IpaffsPostalAddressMapper.Map(from?.PostalAddress);
                	return to;
	}
}

