//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsCommodityChecksMapper
{
	public static Tdm.Model.Ipaffs.IpaffsCommodityChecks Map(Tdm.Types.Ipaffs.IpaffsCommodityChecks from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsCommodityChecks ();
to.UniqueComplementId = from.UniqueComplementId;
            to.Checks = from?.Checks?.Select(x => IpaffsInspectionCheckMapper.Map(x)).ToArray();
                to.ValidityPeriod = from.ValidityPeriod;
            	return to;
	}
}

