//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsCommodityRiskResultPhsiDecisionEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsCommodityRiskResultPhsiDecisionEnum? Map(Tdm.Types.Ipaffs.IpaffsCommodityRiskResultPhsiDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsCommodityRiskResultPhsiDecisionEnum.Required => Tdm.Model.Ipaffs.IpaffsCommodityRiskResultPhsiDecisionEnum.Required,
    Tdm.Types.Ipaffs.IpaffsCommodityRiskResultPhsiDecisionEnum.Notrequired => Tdm.Model.Ipaffs.IpaffsCommodityRiskResultPhsiDecisionEnum.Notrequired,
     
};
}
        

}


