//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsCatchCertificateAttachmentMapper
{
	public static Tdm.Model.Ipaffs.IpaffsCatchCertificateAttachment Map(Tdm.Types.Ipaffs.IpaffsCatchCertificateAttachment from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsCatchCertificateAttachment ();
to.AttachmentId = from.AttachmentId;
            to.NumberOfCatchCertificates = from.NumberOfCatchCertificates;
            to.CatchCertificateDetails = from?.CatchCertificateDetails?.Select(x => IpaffsCatchCertificateDetailsMapper.Map(x)).ToArray();
                	return to;
	}
}

