//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsControlAuthorityMapper
{
	public static Tdm.Model.Ipaffs.IpaffsControlAuthority Map(Tdm.Types.Ipaffs.IpaffsControlAuthority from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsControlAuthority ();
to.OfficialVeterinarian = IpaffsOfficialVeterinarianMapper.Map(from?.OfficialVeterinarian);
                to.CustomsReferenceNo = from.CustomsReferenceNo;
            to.ContainerResealed = from.ContainerResealed;
            to.NewSealNumber = from.NewSealNumber;
            to.IuuFishingReference = from.IuuFishingReference;
            to.IuuCheckRequired = from.IuuCheckRequired;
            to.IuuOption = IpaffsControlAuthorityIuuOptionEnumMapper.Map(from?.IuuOption);
                	return to;
	}
}

