//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsDecisionNotAcceptableActionDestructionReasonEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum? Map(Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.ContaminatedProducts => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.ContaminatedProducts,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.InterceptedPart => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.InterceptedPart,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.PackagingMaterial => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.PackagingMaterial,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.Other => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionDestructionReasonEnum.Other,
     
};
}
        

}


