//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsLaboratoryTestResultConclusionEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum? Map(Tdm.Types.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.Satisfactory => Tdm.Model.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.Satisfactory,
    Tdm.Types.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.NotSatisfactory => Tdm.Model.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.NotSatisfactory,
    Tdm.Types.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.NotInterpretable => Tdm.Model.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.NotInterpretable,
    Tdm.Types.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.Pending => Tdm.Model.Ipaffs.IpaffsLaboratoryTestResultConclusionEnum.Pending,
     
};
}
        

}


