//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsConsignmentCheckMapper
{
	public static Tdm.Model.Ipaffs.IpaffsConsignmentCheck Map(Tdm.Types.Ipaffs.IpaffsConsignmentCheck from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsConsignmentCheck ();
to.EuStandard = from.EuStandard;
            to.AdditionalGuarantees = from.AdditionalGuarantees;
            to.DocumentCheckResult = from.DocumentCheckResult;
            to.NationalRequirements = from.NationalRequirements;
            to.IdentityCheckDone = from.IdentityCheckDone;
            to.IdentityCheckType = IpaffsConsignmentCheckIdentityCheckTypeEnumMapper.Map(from?.IdentityCheckType);
                to.IdentityCheckResult = from.IdentityCheckResult;
            to.IdentityCheckNotDoneReason = IpaffsConsignmentCheckIdentityCheckNotDoneReasonEnumMapper.Map(from?.IdentityCheckNotDoneReason);
                to.PhysicalCheckDone = from.PhysicalCheckDone;
            to.PhysicalCheckResult = from.PhysicalCheckResult;
            to.PhysicalCheckNotDoneReason = IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnumMapper.Map(from?.PhysicalCheckNotDoneReason);
                to.PhysicalCheckOtherText = from.PhysicalCheckOtherText;
            to.WelfareCheck = from.WelfareCheck;
            to.NumberOfAnimalsChecked = from.NumberOfAnimalsChecked;
            to.LaboratoryCheckDone = from.LaboratoryCheckDone;
            to.LaboratoryCheckResult = from.LaboratoryCheckResult;
            	return to;
	}
}

