//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsUnitEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsUnitEnum Map(Tdm.Types.Ipaffs.IpaffsUnitEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsUnitEnum.Percent => Tdm.Model.Ipaffs.IpaffsUnitEnum.Percent,
    Tdm.Types.Ipaffs.IpaffsUnitEnum.Number => Tdm.Model.Ipaffs.IpaffsUnitEnum.Number,
     
};
}
        

}


