//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsPartOneTypeOfImpEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsPartOneTypeOfImpEnum? Map(Tdm.Types.Ipaffs.IpaffsPartOneTypeOfImpEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsPartOneTypeOfImpEnum.A => Tdm.Model.Ipaffs.IpaffsPartOneTypeOfImpEnum.A,
    Tdm.Types.Ipaffs.IpaffsPartOneTypeOfImpEnum.P => Tdm.Model.Ipaffs.IpaffsPartOneTypeOfImpEnum.P,
    Tdm.Types.Ipaffs.IpaffsPartOneTypeOfImpEnum.D => Tdm.Model.Ipaffs.IpaffsPartOneTypeOfImpEnum.D,
     
};
}
        

}


