//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsLaboratoryTestsTestReasonEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum? Map(Tdm.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.Random => Tdm.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.Random,
    Tdm.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.Suspicious => Tdm.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.Suspicious,
    Tdm.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.ReEnforced => Tdm.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.ReEnforced,
    Tdm.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.IntensifiedControls => Tdm.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.IntensifiedControls,
    Tdm.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.Required => Tdm.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.Required,
    Tdm.Types.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.LatentInfectionSampling => Tdm.Model.Ipaffs.IpaffsLaboratoryTestsTestReasonEnum.LatentInfectionSampling,
     
};
}
        

}


