//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsDetailsOnReExportMapper
{
	public static Tdm.Model.Ipaffs.IpaffsDetailsOnReExport Map(Tdm.Types.Ipaffs.IpaffsDetailsOnReExport from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsDetailsOnReExport ();
to.Date = from.Date;
            to.MeansOfTransportNo = from.MeansOfTransportNo;
            to.TransportType = IpaffsDetailsOnReExportTransportTypeEnumMapper.Map(from?.TransportType);
                to.Document = from.Document;
            to.CountryOfReDispatching = from.CountryOfReDispatching;
            to.ExitBip = from.ExitBip;
            	return to;
	}
}

