//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum Map(Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.ContaminatedProducts => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.ContaminatedProducts,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.InterceptedPart => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.InterceptedPart,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.PackagingMaterial => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.PackagingMaterial,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.Other => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionQuarantineImposedReasonEnum.Other,
     
};
}
        

}


