//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsCommodityComplementMapper
{
	public static Tdm.Model.Ipaffs.IpaffsCommodityComplement Map(Tdm.Types.Ipaffs.IpaffsCommodityComplement from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsCommodityComplement ();
to.UniqueComplementId = from.UniqueComplementId;
            to.CommodityDescription = from.CommodityDescription;
            to.CommodityId = from.CommodityId;
            to.ComplementId = from.ComplementId;
            to.ComplementName = from.ComplementName;
            to.EppoCode = from.EppoCode;
            to.IsWoodPackaging = from.IsWoodPackaging;
            to.SpeciesId = from.SpeciesId;
            to.SpeciesName = from.SpeciesName;
            to.SpeciesNomination = from.SpeciesNomination;
            to.SpeciesTypeName = from.SpeciesTypeName;
            to.SpeciesType = from.SpeciesType;
            to.SpeciesClassName = from.SpeciesClassName;
            to.SpeciesClass = from.SpeciesClass;
            to.SpeciesFamilyName = from.SpeciesFamilyName;
            to.SpeciesFamily = from.SpeciesFamily;
            to.SpeciesCommonName = from.SpeciesCommonName;
            to.IsCdsMatched = from.IsCdsMatched;
            	return to;
	}
}

