//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsInspectionCheckMapper
{
	public static Tdm.Model.Ipaffs.IpaffsInspectionCheck Map(Tdm.Types.Ipaffs.IpaffsInspectionCheck from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsInspectionCheck ();
to.IpaffsType = IpaffsInspectionCheckTypeEnumMapper.Map(from?.IpaffsType);
                to.Status = IpaffsInspectionCheckStatusEnumMapper.Map(from?.Status);
                to.Reason = from.Reason;
            to.OtherReason = from.OtherReason;
            to.IsSelectedForChecks = from.IsSelectedForChecks;
            to.HasChecksComplete = from.HasChecksComplete;
            	return to;
	}
}

