//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsDecisionNotAcceptableActionReDispatchReasonEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum? Map(Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.ContaminatedProducts => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.ContaminatedProducts,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.InterceptedPart => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.InterceptedPart,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.PackagingMaterial => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.PackagingMaterial,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.MeansOfTransport => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.MeansOfTransport,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.Other => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionReDispatchReasonEnum.Other,
     
};
}
        

}


