//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsJourneyRiskCategorisationResultRiskLevelMethodEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelMethodEnum Map(Tdm.Types.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelMethodEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelMethodEnum.System => Tdm.Model.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelMethodEnum.System,
    Tdm.Types.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelMethodEnum.User => Tdm.Model.Ipaffs.IpaffsJourneyRiskCategorisationResultRiskLevelMethodEnum.User,
     
};
}
        

}


