//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsPartThreeControlStatusEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsPartThreeControlStatusEnum? Map(Tdm.Types.Ipaffs.IpaffsPartThreeControlStatusEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsPartThreeControlStatusEnum.Required => Tdm.Model.Ipaffs.IpaffsPartThreeControlStatusEnum.Required,
    Tdm.Types.Ipaffs.IpaffsPartThreeControlStatusEnum.Completed => Tdm.Model.Ipaffs.IpaffsPartThreeControlStatusEnum.Completed,
     
};
}
        

}


