//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsFeedbackInformationMapper
{
	public static Tdm.Model.Ipaffs.IpaffsFeedbackInformation Map(Tdm.Types.Ipaffs.IpaffsFeedbackInformation from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsFeedbackInformation ();
to.AuthorityType = IpaffsFeedbackInformationAuthorityTypeEnumMapper.Map(from?.AuthorityType);
                to.ConsignmentArrival = from.ConsignmentArrival;
            to.ConsignmentConformity = from.ConsignmentConformity;
            to.ConsignmentNoArrivalReason = from.ConsignmentNoArrivalReason;
            to.DestructionDate = from.DestructionDate;
            	return to;
	}
}

