//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsCommodityRiskResultExitRiskDecisionEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum Map(Tdm.Types.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum.Required => Tdm.Model.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum.Required,
    Tdm.Types.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum.Notrequired => Tdm.Model.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum.Notrequired,
    Tdm.Types.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum.Inconclusive => Tdm.Model.Ipaffs.IpaffsCommodityRiskResultExitRiskDecisionEnum.Inconclusive,
     
};
}
        

}


