//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsCommodityRiskResultRiskDecisionEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum? Map(Tdm.Types.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.Required => Tdm.Model.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.Required,
    Tdm.Types.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.Notrequired => Tdm.Model.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.Notrequired,
    Tdm.Types.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.Inconclusive => Tdm.Model.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.Inconclusive,
    Tdm.Types.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.ReenforcedCheck => Tdm.Model.Ipaffs.IpaffsCommodityRiskResultRiskDecisionEnum.ReenforcedCheck,
     
};
}
        

}


