//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum? Map(Tdm.Types.Ipaffs.IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum.ReducedChecksRegime => Tdm.Model.Ipaffs.IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum.ReducedChecksRegime,
    Tdm.Types.Ipaffs.IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum.Other => Tdm.Model.Ipaffs.IpaffsConsignmentCheckPhysicalCheckNotDoneReasonEnum.Other,
     
};
}
        

}


