//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsPurposePurposeGroupEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsPurposePurposeGroupEnum Map(Tdm.Types.Ipaffs.IpaffsPurposePurposeGroupEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForImport => Tdm.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForImport,
    Tdm.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForNONConformingConsignments => Tdm.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForNONConformingConsignments,
    Tdm.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForTranshipmentTo => Tdm.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForTranshipmentTo,
    Tdm.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForTransitTo3rdCountry => Tdm.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForTransitTo3rdCountry,
    Tdm.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForReImport => Tdm.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForReImport,
    Tdm.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForPrivateImport => Tdm.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForPrivateImport,
    Tdm.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForTransferTo => Tdm.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForTransferTo,
    Tdm.Types.Ipaffs.IpaffsPurposePurposeGroupEnum.ForImportReConformityCheck => Tdm.Model.Ipaffs.IpaffsPurposePurposeGroupEnum.ForImportReConformityCheck,
     
};
}
        

}


