//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsUserInformationMapper
{
	public static Tdm.Model.Ipaffs.IpaffsUserInformation Map(Tdm.Types.Ipaffs.IpaffsUserInformation from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsUserInformation ();
to.DisplayName = from.DisplayName;
            to.UserId = from.UserId;
            to.IsControlUser = from.IsControlUser;
            	return to;
	}
}

