//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsCommodityRiskResultMapper
{
	public static Tdm.Model.Ipaffs.IpaffsCommodityRiskResult Map(Tdm.Types.Ipaffs.IpaffsCommodityRiskResult from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsCommodityRiskResult ();
to.RiskDecision = IpaffsCommodityRiskResultRiskDecisionEnumMapper.Map(from?.RiskDecision);
                to.ExitRiskDecision = IpaffsCommodityRiskResultExitRiskDecisionEnumMapper.Map(from?.ExitRiskDecision);
                to.HmiDecision = IpaffsCommodityRiskResultHmiDecisionEnumMapper.Map(from?.HmiDecision);
                to.PhsiDecision = IpaffsCommodityRiskResultPhsiDecisionEnumMapper.Map(from?.PhsiDecision);
                to.PhsiClassification = IpaffsCommodityRiskResultPhsiClassificationEnumMapper.Map(from?.PhsiClassification);
                to.Phsi = IpaffsPhsiMapper.Map(from?.Phsi);
                to.UniqueId = from.UniqueId;
            to.EppoCode = from.EppoCode;
            to.Variety = from.Variety;
            to.IsWoody = from.IsWoody;
            to.IndoorOutdoor = from.IndoorOutdoor;
            to.Propagation = from.Propagation;
            to.PhsiRuleType = from.PhsiRuleType;
            	return to;
	}
}

