//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsExternalReferenceSystemEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsExternalReferenceSystemEnum? Map(Tdm.Types.Ipaffs.IpaffsExternalReferenceSystemEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsExternalReferenceSystemEnum.Ecert => Tdm.Model.Ipaffs.IpaffsExternalReferenceSystemEnum.Ecert,
    Tdm.Types.Ipaffs.IpaffsExternalReferenceSystemEnum.Ephyto => Tdm.Model.Ipaffs.IpaffsExternalReferenceSystemEnum.Ephyto,
    Tdm.Types.Ipaffs.IpaffsExternalReferenceSystemEnum.Enotification => Tdm.Model.Ipaffs.IpaffsExternalReferenceSystemEnum.Enotification,
    Tdm.Types.Ipaffs.IpaffsExternalReferenceSystemEnum.Ncts => Tdm.Model.Ipaffs.IpaffsExternalReferenceSystemEnum.Ncts,
     
};
}
        

}


