//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsChedppNotAcceptableReasonCommodityOrPackageEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum? Map(Tdm.Types.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum.C => Tdm.Model.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum.C,
    Tdm.Types.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum.P => Tdm.Model.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum.P,
    Tdm.Types.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum.Cp => Tdm.Model.Ipaffs.IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum.Cp,
     
};
}
        

}


