//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsControlConsignmentLeaveEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsControlConsignmentLeaveEnum Map(Tdm.Types.Ipaffs.IpaffsControlConsignmentLeaveEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsControlConsignmentLeaveEnum.Yes => Tdm.Model.Ipaffs.IpaffsControlConsignmentLeaveEnum.Yes,
    Tdm.Types.Ipaffs.IpaffsControlConsignmentLeaveEnum.No => Tdm.Model.Ipaffs.IpaffsControlConsignmentLeaveEnum.No,
    Tdm.Types.Ipaffs.IpaffsControlConsignmentLeaveEnum.ItHasBeenDestroyed => Tdm.Model.Ipaffs.IpaffsControlConsignmentLeaveEnum.ItHasBeenDestroyed,
     
};
}
        

}


