//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum? Map(Tdm.Types.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.CustomWarehouse => Tdm.Model.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.CustomWarehouse,
    Tdm.Types.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.FreeZoneOrFreeWarehouse => Tdm.Model.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.FreeZoneOrFreeWarehouse,
    Tdm.Types.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.ShipSupplier => Tdm.Model.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.ShipSupplier,
    Tdm.Types.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.Ship => Tdm.Model.Ipaffs.IpaffsDecisionSpecificWarehouseNonConformingConsignmentEnum.Ship,
     
};
}
        

}


