//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsComplementParameterSetMapper
{
	public static Tdm.Model.Ipaffs.IpaffsComplementParameterSet Map(Tdm.Types.Ipaffs.IpaffsComplementParameterSet from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsComplementParameterSet ();
to.UniqueComplementId = from.UniqueComplementId;
            to.ComplementId = from.ComplementId;
            to.SpeciesId = from.SpeciesId;
            to.KeyDataPairs = Tdm.Types.Ipaffs.Mapping.DictionaryMapper.Map(from?.KeyDataPairs);
        to.CatchCertificates = from?.CatchCertificates?.Select(x => IpaffsCatchCertificatesMapper.Map(x)).ToArray();
                to.Identifiers = from?.Identifiers?.Select(x => IpaffsIdentifiersMapper.Map(x)).ToArray();
                	return to;
	}
}

