//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsCommodityRiskResultPhsiClassificationEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum? Map(Tdm.Types.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum.Mandatory => Tdm.Model.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum.Mandatory,
    Tdm.Types.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum.Reduced => Tdm.Model.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum.Reduced,
    Tdm.Types.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum.Controlled => Tdm.Model.Ipaffs.IpaffsCommodityRiskResultPhsiClassificationEnum.Controlled,
     
};
}
        

}


