//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsCommoditiesCommodityIntendedForEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum Map(Tdm.Types.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Human => Tdm.Model.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Human,
    Tdm.Types.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Feedingstuff => Tdm.Model.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Feedingstuff,
    Tdm.Types.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Further => Tdm.Model.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Further,
    Tdm.Types.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Other => Tdm.Model.Ipaffs.IpaffsCommoditiesCommodityIntendedForEnum.Other,
     
};
}
        

}


