//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsKeyDataPairMapper
{
	public static Tdm.Model.Ipaffs.IpaffsKeyDataPair Map(Tdm.Types.Ipaffs.IpaffsKeyDataPair from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsKeyDataPair ();
to.Key = from.Key;
            to.Data = from.Data;
            	return to;
	}
}

