//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsRiskAssessmentResultMapper
{
	public static Tdm.Model.Ipaffs.IpaffsRiskAssessmentResult Map(Tdm.Types.Ipaffs.IpaffsRiskAssessmentResult from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsRiskAssessmentResult ();
to.CommodityResults = from?.CommodityResults?.Select(x => IpaffsCommodityRiskResultMapper.Map(x)).ToArray();
                to.AssessmentDateTime = from.AssessmentDateTime;
            	return to;
	}
}

