//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsInspectionCheckTypeEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsInspectionCheckTypeEnum Map(Tdm.Types.Ipaffs.IpaffsInspectionCheckTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsInspectionCheckTypeEnum.PhsiDocument => Tdm.Model.Ipaffs.IpaffsInspectionCheckTypeEnum.PhsiDocument,
    Tdm.Types.Ipaffs.IpaffsInspectionCheckTypeEnum.PhsiIdentity => Tdm.Model.Ipaffs.IpaffsInspectionCheckTypeEnum.PhsiIdentity,
    Tdm.Types.Ipaffs.IpaffsInspectionCheckTypeEnum.PhsiPhysical => Tdm.Model.Ipaffs.IpaffsInspectionCheckTypeEnum.PhsiPhysical,
    Tdm.Types.Ipaffs.IpaffsInspectionCheckTypeEnum.Hmi => Tdm.Model.Ipaffs.IpaffsInspectionCheckTypeEnum.Hmi,
     
};
}
        

}


