//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsDetailsOnReExportTransportTypeEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum? Map(Tdm.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Rail => Tdm.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Rail,
    Tdm.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Plane => Tdm.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Plane,
    Tdm.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Ship => Tdm.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Ship,
    Tdm.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Road => Tdm.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Road,
    Tdm.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Other => Tdm.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.Other,
    Tdm.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.CShipRoad => Tdm.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.CShipRoad,
    Tdm.Types.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.CShipRail => Tdm.Model.Ipaffs.IpaffsDetailsOnReExportTransportTypeEnum.CShipRail,
     
};
}
        

}


