//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsConsignmentCheckIdentityCheckTypeEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum? Map(Tdm.Types.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum.SealCheck => Tdm.Model.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum.SealCheck,
    Tdm.Types.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum.FullIdentityCheck => Tdm.Model.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum.FullIdentityCheck,
    Tdm.Types.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum.NotDone => Tdm.Model.Ipaffs.IpaffsConsignmentCheckIdentityCheckTypeEnum.NotDone,
     
};
}
        

}


