//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsDecisionIfChanneledOptionEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsDecisionIfChanneledOptionEnum? Map(Tdm.Types.Ipaffs.IpaffsDecisionIfChanneledOptionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsDecisionIfChanneledOptionEnum.Article8 => Tdm.Model.Ipaffs.IpaffsDecisionIfChanneledOptionEnum.Article8,
    Tdm.Types.Ipaffs.IpaffsDecisionIfChanneledOptionEnum.Article15 => Tdm.Model.Ipaffs.IpaffsDecisionIfChanneledOptionEnum.Article15,
     
};
}
        

}


