//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsResultEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsResultEnum Map(Tdm.Types.Ipaffs.IpaffsResultEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsResultEnum.Satisfactory => Tdm.Model.Ipaffs.IpaffsResultEnum.Satisfactory,
    Tdm.Types.Ipaffs.IpaffsResultEnum.SatisfactoryFollowingOfficialIntervention => Tdm.Model.Ipaffs.IpaffsResultEnum.SatisfactoryFollowingOfficialIntervention,
    Tdm.Types.Ipaffs.IpaffsResultEnum.NotSatisfactory => Tdm.Model.Ipaffs.IpaffsResultEnum.NotSatisfactory,
    Tdm.Types.Ipaffs.IpaffsResultEnum.NotDone => Tdm.Model.Ipaffs.IpaffsResultEnum.NotDone,
    Tdm.Types.Ipaffs.IpaffsResultEnum.Derogation => Tdm.Model.Ipaffs.IpaffsResultEnum.Derogation,
    Tdm.Types.Ipaffs.IpaffsResultEnum.NotSet => Tdm.Model.Ipaffs.IpaffsResultEnum.NotSet,
     
};
}
        

}


