//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsPartThreeMapper
{
	public static Tdm.Model.Ipaffs.IpaffsPartThree Map(Tdm.Types.Ipaffs.IpaffsPartThree from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsPartThree ();
to.ControlStatus = IpaffsPartThreeControlStatusEnumMapper.Map(from?.ControlStatus);
                to.Control = IpaffsControlMapper.Map(from?.Control);
                to.ConsignmentValidations = from?.ConsignmentValidations?.Select(x => IpaffsValidationMessageCodeMapper.Map(x)).ToArray();
                to.SealCheckRequired = from.SealCheckRequired;
            to.SealCheck = IpaffsSealCheckMapper.Map(from?.SealCheck);
                to.SealCheckOverride = IpaffsInspectionOverrideMapper.Map(from?.SealCheckOverride);
                	return to;
	}
}

