//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsEconomicOperatorStatusEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsEconomicOperatorStatusEnum Map(Tdm.Types.Ipaffs.IpaffsEconomicOperatorStatusEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsEconomicOperatorStatusEnum.Approved => Tdm.Model.Ipaffs.IpaffsEconomicOperatorStatusEnum.Approved,
    Tdm.Types.Ipaffs.IpaffsEconomicOperatorStatusEnum.Nonapproved => Tdm.Model.Ipaffs.IpaffsEconomicOperatorStatusEnum.Nonapproved,
    Tdm.Types.Ipaffs.IpaffsEconomicOperatorStatusEnum.Suspended => Tdm.Model.Ipaffs.IpaffsEconomicOperatorStatusEnum.Suspended,
     
};
}
        

}


