//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsDecisionDecisionEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsDecisionDecisionEnum? Map(Tdm.Types.Ipaffs.IpaffsDecisionDecisionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsDecisionDecisionEnum.NonAcceptable => Tdm.Model.Ipaffs.IpaffsDecisionDecisionEnum.NonAcceptable,
    Tdm.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForInternalMarket => Tdm.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForInternalMarket,
    Tdm.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableIfChanneled => Tdm.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableIfChanneled,
    Tdm.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTranshipment => Tdm.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTranshipment,
    Tdm.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTransit => Tdm.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTransit,
    Tdm.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTemporaryImport => Tdm.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTemporaryImport,
    Tdm.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForSpecificWarehouse => Tdm.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForSpecificWarehouse,
    Tdm.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForPrivateImport => Tdm.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForPrivateImport,
    Tdm.Types.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTransfer => Tdm.Model.Ipaffs.IpaffsDecisionDecisionEnum.AcceptableForTransfer,
    Tdm.Types.Ipaffs.IpaffsDecisionDecisionEnum.HorseReEntry => Tdm.Model.Ipaffs.IpaffsDecisionDecisionEnum.HorseReEntry,
     
};
}
        

}


