//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsPartyMapper
{
	public static Tdm.Model.Ipaffs.IpaffsParty Map(Tdm.Types.Ipaffs.IpaffsParty from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsParty ();
to.IpaffsId = from.IpaffsId;
            to.Name = from.Name;
            to.CompanyId = from.CompanyId;
            to.ContactId = from.ContactId;
            to.CompanyName = from.CompanyName;
            to.Addresses = from.Addresses;
            to.County = from.County;
            to.PostCode = from.PostCode;
            to.Country = from.Country;
            to.City = from.City;
            to.TracesId = from.TracesId;
            to.IpaffsType = IpaffsPartyTypeEnumMapper.Map(from?.IpaffsType);
                to.ApprovalNumber = from.ApprovalNumber;
            to.Phone = from.Phone;
            to.Fax = from.Fax;
            to.Email = from.Email;
            	return to;
	}
}

