//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsFeedbackInformationAuthorityTypeEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum? Map(Tdm.Types.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Exitbip => Tdm.Model.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Exitbip,
    Tdm.Types.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Finalbip => Tdm.Model.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Finalbip,
    Tdm.Types.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Localvetunit => Tdm.Model.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Localvetunit,
    Tdm.Types.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Inspunit => Tdm.Model.Ipaffs.IpaffsFeedbackInformationAuthorityTypeEnum.Inspunit,
     
};
}
        

}


