//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsControlAuthorityIuuOptionEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsControlAuthorityIuuOptionEnum Map(Tdm.Types.Ipaffs.IpaffsControlAuthorityIuuOptionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsControlAuthorityIuuOptionEnum.Iuuok => Tdm.Model.Ipaffs.IpaffsControlAuthorityIuuOptionEnum.Iuuok,
    Tdm.Types.Ipaffs.IpaffsControlAuthorityIuuOptionEnum.Iuuna => Tdm.Model.Ipaffs.IpaffsControlAuthorityIuuOptionEnum.Iuuna,
    Tdm.Types.Ipaffs.IpaffsControlAuthorityIuuOptionEnum.IUUNotCompliant => Tdm.Model.Ipaffs.IpaffsControlAuthorityIuuOptionEnum.IUUNotCompliant,
     
};
}
        

}


