//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsNotificationStatusEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum Map(Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum.Draft => Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum.Draft,
    Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum.Submitted => Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum.Submitted,
    Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum.Validated => Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum.Validated,
    Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum.Rejected => Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum.Rejected,
    Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum.InProgress => Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum.InProgress,
    Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum.Amend => Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum.Amend,
    Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum.Modify => Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum.Modify,
    Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum.Replaced => Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum.Replaced,
    Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum.Cancelled => Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum.Cancelled,
    Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum.Deleted => Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum.Deleted,
    Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum.PartiallyRejected => Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum.PartiallyRejected,
    Tdm.Types.Ipaffs.IpaffsNotificationStatusEnum.SplitConsignment => Tdm.Model.Ipaffs.IpaffsNotificationStatusEnum.SplitConsignment,
     
};
}
        

}


