//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum Map(Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.ContaminatedProducts => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.ContaminatedProducts,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.InterceptedPart => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.InterceptedPart,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.PackagingMaterial => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.PackagingMaterial,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.MeansOfTransport => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.MeansOfTransport,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.Other => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionUseForOtherPurposesReasonEnum.Other,
     
};
}
        

}


