//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsAnimalCertificationEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum? Map(Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.AnimalFeedingStuff => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.AnimalFeedingStuff,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Approved => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Approved,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.ArtificialReproduction => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.ArtificialReproduction,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Breeding => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Breeding,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Circus => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Circus,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.CommercialSale => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.CommercialSale,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.CommercialSaleOrChangeOfOwnership => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.CommercialSaleOrChangeOfOwnership,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Fattening => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Fattening,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.GameRestocking => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.GameRestocking,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.HumanConsumption => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.HumanConsumption,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.InternalMarket => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.InternalMarket,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Other => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Other,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.PersonallyOwnedPetsNotForRehoming => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.PersonallyOwnedPetsNotForRehoming,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Pets => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Pets,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Production => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Production,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Quarantine => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Quarantine,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.RacingCompetition => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.RacingCompetition,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.RegisteredEquidae => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.RegisteredEquidae,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Registered => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Registered,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.RejectedOrReturnedConsignment => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.RejectedOrReturnedConsignment,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Relaying => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Relaying,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.RescueRehoming => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.RescueRehoming,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Research => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Research,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Slaughter => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Slaughter,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.TechnicalPharmaceuticalUse => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.TechnicalPharmaceuticalUse,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.Transit => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.Transit,
    Tdm.Types.Ipaffs.IpaffsAnimalCertificationEnum.ZooCollection => Tdm.Model.Ipaffs.IpaffsAnimalCertificationEnum.ZooCollection,
     
};
}
        

}


