//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsInspectorMapper
{
	public static Tdm.Model.Ipaffs.IpaffsInspector Map(Tdm.Types.Ipaffs.IpaffsInspector from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsInspector ();
to.Name = from.Name;
            to.Phone = from.Phone;
            to.Email = from.Email;
            	return to;
	}
}

