//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsDecisionNotAcceptableActionEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum? Map(Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Slaughter => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Slaughter,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Reexport => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Reexport,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Euthanasia => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Euthanasia,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Redispatching => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Redispatching,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Destruction => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Destruction,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Transformation => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Transformation,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Other => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.Other,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.EntryRefusal => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.EntryRefusal,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.QuarantineImposed => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.QuarantineImposed,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.SpecialTreatment => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.SpecialTreatment,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.IndustrialProcessing => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.IndustrialProcessing,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.ReDispatch => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.ReDispatch,
    Tdm.Types.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.UseForOtherPurposes => Tdm.Model.Ipaffs.IpaffsDecisionNotAcceptableActionEnum.UseForOtherPurposes,
     
};
}
        

}


