//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsSealContainerMapper
{
	public static Tdm.Model.Ipaffs.IpaffsSealContainer Map(Tdm.Types.Ipaffs.IpaffsSealContainer from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsSealContainer ();
to.SealNumber = from.SealNumber;
            to.ContainerNumber = from.ContainerNumber;
            to.OfficialSeal = from.OfficialSeal;
            to.ResealedSealNumber = from.ResealedSealNumber;
            	return to;
	}
}

