//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsNotificationTypeEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsNotificationTypeEnum? Map(Tdm.Types.Ipaffs.IpaffsNotificationTypeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsNotificationTypeEnum.Cveda => Tdm.Model.Ipaffs.IpaffsNotificationTypeEnum.Cveda,
    Tdm.Types.Ipaffs.IpaffsNotificationTypeEnum.Cvedp => Tdm.Model.Ipaffs.IpaffsNotificationTypeEnum.Cvedp,
    Tdm.Types.Ipaffs.IpaffsNotificationTypeEnum.Chedpp => Tdm.Model.Ipaffs.IpaffsNotificationTypeEnum.Chedpp,
    Tdm.Types.Ipaffs.IpaffsNotificationTypeEnum.Ced => Tdm.Model.Ipaffs.IpaffsNotificationTypeEnum.Ced,
    Tdm.Types.Ipaffs.IpaffsNotificationTypeEnum.Imp => Tdm.Model.Ipaffs.IpaffsNotificationTypeEnum.Imp,
     
};
}
        

}


