//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated from a template.
	//
	//     Manual changes to this file may cause unexpected behavior in your application.
	//     Manual changes to this file will be overwritten if the code is regenerated.
	//
//</auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsIdentifiersMapper
{
	public static Tdm.Model.Ipaffs.IpaffsIdentifiers Map(Tdm.Types.Ipaffs.IpaffsIdentifiers from)
	{
	if(from is null)
	{
		return default!;
	}
		var to = new Tdm.Model.Ipaffs.IpaffsIdentifiers ();
to.SpeciesNumber = from.SpeciesNumber;
            to.Data = from.Data;
            to.IsPlaceOfDestinationThePermanentAddress = from.IsPlaceOfDestinationThePermanentAddress;
            to.PermanentAddress = IpaffsEconomicOperatorMapper.Map(from?.PermanentAddress);
                	return to;
	}
}

