//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
#nullable enable


namespace Tdm.Types.Ipaffs;

public static class IpaffsDecisionFreeCirculationPurposeEnumMapper
{
public static Tdm.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum? Map(Tdm.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum? from)
{
if(from == null)
{
return default!;
}
return from switch
{
Tdm.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.AnimalFeedingStuff => Tdm.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.AnimalFeedingStuff,
    Tdm.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.HumanConsumption => Tdm.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.HumanConsumption,
    Tdm.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.PharmaceuticalUse => Tdm.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.PharmaceuticalUse,
    Tdm.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.TechnicalUse => Tdm.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.TechnicalUse,
    Tdm.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.FurtherProcess => Tdm.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.FurtherProcess,
    Tdm.Types.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.Other => Tdm.Model.Ipaffs.IpaffsDecisionFreeCirculationPurposeEnum.Other,
     
};
}
        

}


