//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace TdmPrototypeBackend.Types.Ipaffs;

/// <summary>
/// Information about not acceptable reason
/// </summary>
public partial class IpaffsChedppNotAcceptableReason  //
{


    /// <summary>
    /// reason for refusal
    /// </summary
    [Attr]
    [JsonPropertyName("reason")]
    public IpaffsChedppNotAcceptableReasonReasonEnum? Reason { get; set; }

	
    /// <summary>
    /// commodity or package
    /// </summary
    [Attr]
    [JsonPropertyName("commodityOrPackage")]
    public IpaffsChedppNotAcceptableReasonCommodityOrPackageEnum? CommodityOrPackage { get; set; }

	}


