//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;

namespace TdmPrototypeBackend.Types.Ipaffs;

    /// <summary>
    /// Information about logged-in user
    /// </summary>
public partial class IpaffsUserInformation  {


        /// <summary>
        /// Display name
        /// </summary>
        [Attr]
        [JsonPropertyName("displayName")]
        public string? DisplayName { get; set; }
    
        /// <summary>
        /// User ID
        /// </summary>
        [Attr]
        [JsonPropertyName("userId")]
        public string? UserId { get; set; }
    
        /// <summary>
        /// Is this user a control
        /// </summary>
        [Attr]
        [JsonPropertyName("isControlUser")]
        public bool? IsControlUser { get; set; }
    
}


