//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;

namespace TdmPrototypeBackend.Types.Ipaffs;

    /// <summary>
    /// Inspector Address
    /// </summary>
public partial class IpaffsAddress  {


        /// <summary>
        /// Street
        /// </summary>
        [Attr]
        [JsonPropertyName("street")]
        public string? Street { get; set; }
    
        /// <summary>
        /// City
        /// </summary>
        [Attr]
        [JsonPropertyName("city")]
        public string? City { get; set; }
    
        /// <summary>
        /// Country
        /// </summary>
        [Attr]
        [JsonPropertyName("country")]
        public string? Country { get; set; }
    
        /// <summary>
        /// Postal Code
        /// </summary>
        [Attr]
        [JsonPropertyName("postalCode")]
        public string? PostalCode { get; set; }
    
}


