//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;

namespace TdmPrototypeBackend.Types.Ipaffs;

    /// <summary>
    /// Feedback information from control
    /// </summary>
public partial class IpaffsFeedbackInformation  {


        /// <summary>
        /// Type of authority
        /// </summary>
        [Attr]
        [JsonPropertyName("authorityType")]
        public IpaffsFeedbackInformationAuthorityTypeEnum? AuthorityType { get; set; }
    
        /// <summary>
        /// Did the consignment arrive
        /// </summary>
        [Attr]
        [JsonPropertyName("consignmentArrival")]
        public bool? ConsignmentArrival { get; set; }
    
        /// <summary>
        /// Does the consignment conform
        /// </summary>
        [Attr]
        [JsonPropertyName("consignmentConformity")]
        public bool? ConsignmentConformity { get; set; }
    
        /// <summary>
        /// Reason for consignment not arriving at the entry point
        /// </summary>
        [Attr]
        [JsonPropertyName("consignmentNoArrivalReason")]
        public string? ConsignmentNoArrivalReason { get; set; }
    
        /// <summary>
        /// Date of consignment destruction
        /// </summary>
        [Attr]
        [JsonPropertyName("destructionDate")]
        public string? DestructionDate { get; set; }
    
}


