//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace TdmPrototypeBackend.Types.Ipaffs;

/// <summary>
/// inspector
/// </summary>
public partial class IpaffsInspector  //
{


    /// <summary>
    /// Name of inspector
    /// </summary
    [Attr]
    [JsonPropertyName("name")]
    [System.ComponentModel.Description("Name of inspector")]
    public string? Name { get; set; }

	
    /// <summary>
    /// Phone number of inspector
    /// </summary
    [Attr]
    [JsonPropertyName("phone")]
    [System.ComponentModel.Description("Phone number of inspector")]
    public string? Phone { get; set; }

	
    /// <summary>
    /// Email address of inspector
    /// </summary
    [Attr]
    [JsonPropertyName("email")]
    [System.ComponentModel.Description("Email address of inspector")]
    public string? Email { get; set; }

	}


