//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace TdmPrototypeBackend.Types.Ipaffs;

/// <summary>
/// Catch certificate details for uploaded attachment
/// </summary>
public partial class IpaffsCatchCertificateDetails  //
{


    /// <summary>
    /// The UUID of the catch certificate
    /// </summary
    [Attr]
    [JsonPropertyName("catchCertificateId")]
    [System.ComponentModel.Description("The UUID of the catch certificate")]
    public string? CatchCertificateId { get; set; }

	
    /// <summary>
    /// Catch certificate reference
    /// </summary
    [Attr]
    [JsonPropertyName("catchCertificateReference")]
    [System.ComponentModel.Description("Catch certificate reference")]
    public string? CatchCertificateReference { get; set; }

	
    /// <summary>
    /// Catch certificate date of issue
    /// </summary
    [Attr]
    [JsonPropertyName("dateOfIssue")]
    [System.ComponentModel.Description("Catch certificate date of issue")]
    public DateTime? DateOfIssue { get; set; }

	
    /// <summary>
    /// Catch certificate flag state of catching vessel(s)
    /// </summary
    [Attr]
    [JsonPropertyName("flagState")]
    [System.ComponentModel.Description("Catch certificate flag state of catching vessel(s)")]
    public string? FlagState { get; set; }

	
    /// <summary>
    /// List of species imported under this catch certificate
    /// </summary
    [Attr]
    [JsonPropertyName("species")]
    [System.ComponentModel.Description("List of species imported under this catch certificate")]
    public string[]? Species { get; set; }

	}


