//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace TdmPrototypeBackend.Types.Ipaffs;

    /// <summary>
    /// Holder for additional parameters of a commodity
    /// </summary>
public partial class IpaffsCommodityComplement  //
{
    [Attr] public Dictionary<string, object> AdditionalData { get; set; } = new Dictionary<string, object>();
	
    [Attr]
    public IpaffsCommodityRiskResult? RiskAssesment { get; set; }
    
    
}


