//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace TdmPrototypeBackend.Types.Ipaffs;

/// <summary>
/// Inspector Address
/// </summary>
public partial class IpaffsAddress  //
{


    /// <summary>
    /// Street
    /// </summary
    [Attr]
    [JsonPropertyName("street")]
    [System.ComponentModel.Description("Street")]
    [TdmPrototypeBackend.Types.Extensions.SensitiveData()]
    public string? Street { get; set; }

	
    /// <summary>
    /// City
    /// </summary
    [Attr]
    [JsonPropertyName("city")]
    [System.ComponentModel.Description("City")]
    [TdmPrototypeBackend.Types.Extensions.SensitiveData()]
    public string? City { get; set; }

	
    /// <summary>
    /// Country
    /// </summary
    [Attr]
    [JsonPropertyName("country")]
    [System.ComponentModel.Description("Country")]
    public string? Country { get; set; }

	
    /// <summary>
    /// Postal Code
    /// </summary
    [Attr]
    [JsonPropertyName("postalCode")]
    [System.ComponentModel.Description("Postal Code")]
    [TdmPrototypeBackend.Types.Extensions.SensitiveData()]
    public string? PostalCode { get; set; }

	
    /// <summary>
    /// 1st line of address
    /// </summary
    [Attr]
    [JsonPropertyName("addressLine1")]
    [System.ComponentModel.Description("1st line of address")]
    [TdmPrototypeBackend.Types.Extensions.SensitiveData()]
    public string? AddressLine1 { get; set; }

	
    /// <summary>
    /// 2nd line of address
    /// </summary
    [Attr]
    [JsonPropertyName("addressLine2")]
    [System.ComponentModel.Description("2nd line of address")]
    [TdmPrototypeBackend.Types.Extensions.SensitiveData()]
    public string? AddressLine2 { get; set; }

	
    /// <summary>
    /// 3rd line of address
    /// </summary
    [Attr]
    [JsonPropertyName("addressLine3")]
    [System.ComponentModel.Description("3rd line of address")]
    [TdmPrototypeBackend.Types.Extensions.SensitiveData()]
    public string? AddressLine3 { get; set; }

	
    /// <summary>
    /// Post / zip code
    /// </summary
    [Attr]
    [JsonPropertyName("postalZipCode")]
    [System.ComponentModel.Description("Post / zip code")]
    [TdmPrototypeBackend.Types.Extensions.SensitiveData()]
    public string? PostalZipCode { get; set; }

	
    /// <summary>
    /// country 2-digits ISO code
    /// </summary
    [Attr]
    [JsonPropertyName("countryISOCode")]
    [System.ComponentModel.Description("country 2-digits ISO code")]
    public string? CountryISOCode { get; set; }

	
    /// <summary>
    /// Email address
    /// </summary
    [Attr]
    [JsonPropertyName("email")]
    [System.ComponentModel.Description("Email address")]
    [TdmPrototypeBackend.Types.Extensions.SensitiveData()]
    public string? Email { get; set; }

	
    /// <summary>
    /// UK phone number
    /// </summary
    [Attr]
    [JsonPropertyName("ukTelephone")]
    [System.ComponentModel.Description("UK phone number")]
    [TdmPrototypeBackend.Types.Extensions.SensitiveData()]
    public string? UkTelephone { get; set; }

	
    /// <summary>
    /// Telephone number
    /// </summary
    [Attr]
    [JsonPropertyName("telephone")]
    [System.ComponentModel.Description("Telephone number")]
    [TdmPrototypeBackend.Types.Extensions.SensitiveData()]
    public string? Telephone { get; set; }

	
    /// <summary>
    /// International phone number
    /// </summary
    [Attr]
    [JsonPropertyName("internationalTelephone")]
    [System.ComponentModel.Description("International phone number")]
    public IpaffsInternationalTelephone? InternationalTelephone { get; set; }

	}


