//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace TdmPrototypeBackend.Types.Ipaffs;

    /// <summary>
    /// Seal container details
    /// </summary>
public partial class IpaffsSealContainer  //
{


		/// <summary>
        /// 
        /// </summary>
        [Attr]
        [JsonPropertyName("sealNumber")]
		public  string? SealNumber { get; set; }
    
		/// <summary>
        /// 
        /// </summary>
        [Attr]
        [JsonPropertyName("containerNumber")]
		public  string? ContainerNumber { get; set; }
    
		/// <summary>
        /// 
        /// </summary>
        [Attr]
        [JsonPropertyName("officialSeal")]
		public  bool? OfficialSeal { get; set; }
    
		/// <summary>
        /// 
        /// </summary>
        [Attr]
        [JsonPropertyName("resealedSealNumber")]
		public  string? ResealedSealNumber { get; set; }
    
}


