//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace TdmPrototypeBackend.Types.Ipaffs;

/// <summary>
/// Information about logged-in user
/// </summary>
public partial class IpaffsUserInformation  //
{


    /// <summary>
    /// Display name
    /// </summary
    [Attr]
    [JsonPropertyName("displayName")]
    [System.ComponentModel.Description("Display name")]
    [TdmPrototypeBackend.Types.Extensions.SensitiveData()]
    public string? DisplayName { get; set; }

	
    /// <summary>
    /// User ID
    /// </summary
    [Attr]
    [JsonPropertyName("userId")]
    [System.ComponentModel.Description("User ID")]
    public string? UserId { get; set; }

	
    /// <summary>
    /// Is this user a control
    /// </summary
    [Attr]
    [JsonPropertyName("isControlUser")]
    [System.ComponentModel.Description("Is this user a control")]
    public bool? IsControlUser { get; set; }

	}


