//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace TdmPrototypeBackend.Types.Ipaffs;

/// <summary>
/// Part 1 - Holds the information related to veterinary checks and details
/// </summary>
public partial class IpaffsVeterinaryInformation  //
{


    /// <summary>
    /// External reference of approved establishments, which relates to a downstream service
    /// </summary
    [Attr]
    [JsonPropertyName("establishmentsOfOriginExternalReference")]
    [System.ComponentModel.Description("External reference of approved establishments, which relates to a downstream service")]
    public IpaffsExternalReference? EstablishmentsOfOriginExternalReference { get; set; }

	
    /// <summary>
    /// List of establishments which were approved by UK to issue veterinary documents
    /// </summary
    [Attr]
    [JsonPropertyName("establishmentsOfOrigin")]
    [System.ComponentModel.Description("List of establishments which were approved by UK to issue veterinary documents")]
    public IpaffsApprovedEstablishment[]? EstablishmentsOfOrigins { get; set; }

	
    /// <summary>
    /// Veterinary document identification
    /// </summary
    [Attr]
    [JsonPropertyName("veterinaryDocument")]
    [System.ComponentModel.Description("Veterinary document identification")]
    public string? VeterinaryDocument { get; set; }

	
    /// <summary>
    /// Veterinary document issue date
    /// </summary
    [Attr]
    [JsonPropertyName("veterinaryDocumentIssueDate")]
    [System.ComponentModel.Description("Veterinary document issue date")]
    public DateOnly? VeterinaryDocumentIssueDate { get; set; }

	
    /// <summary>
    /// Additional documents
    /// </summary
    [Attr]
    [JsonPropertyName("accompanyingDocumentNumbers")]
    [System.ComponentModel.Description("Additional documents")]
    public string[]? AccompanyingDocumentNumbers { get; set; }

	
    /// <summary>
    /// Accompanying documents
    /// </summary
    [Attr]
    [JsonPropertyName("accompanyingDocuments")]
    [System.ComponentModel.Description("Accompanying documents")]
    public IpaffsAccompanyingDocument[]? AccompanyingDocuments { get; set; }

	
    /// <summary>
    /// Catch certificate attachments
    /// </summary
    [Attr]
    [JsonPropertyName("catchCertificateAttachments")]
    [System.ComponentModel.Description("Catch certificate attachments")]
    public IpaffsCatchCertificateAttachment[]? CatchCertificateAttachments { get; set; }

	
    /// <summary>
    /// Details helpful for identification
    /// </summary
    [Attr]
    [JsonPropertyName("identificationDetails")]
    [System.ComponentModel.Description("Details helpful for identification")]
    public IpaffsIdentificationDetails[]? IdentificationDetails { get; set; }

	}


