//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using JsonApiDotNetCore.Resources.Annotations;
using System.Text.Json.Serialization;
using System.Dynamic;


namespace TdmPrototypeBackend.Types.Ipaffs;

/// <summary>
/// 
/// </summary>
public partial class IpaffsCatchCertificates  //
{


    /// <summary>
    /// The catch certificate number
    /// </summary
    [Attr]
    [JsonPropertyName("certificateNumber")]
    [System.ComponentModel.Description("The catch certificate number")]
    public string? CertificateNumber { get; set; }

	
    /// <summary>
    /// The catch certificate weight number
    /// </summary
    [Attr]
    [JsonPropertyName("weight")]
    [System.ComponentModel.Description("The catch certificate weight number")]
    public double? Weight { get; set; }

	}


